// ============================================================
// Banco de Dados de Teses Tributárias — Evox Fiscal
// Teses reais do cenário tributário brasileiro
// ============================================================

import { Tese } from './types';

export const tesesDatabase: Tese[] = [
  {
    id: 'tese-001',
    nome: 'Exclusão do ICMS da Base de Cálculo do PIS/COFINS',
    tributoEnvolvido: 'PIS/COFINS',
    tipo: 'tese_judicial',
    classificacao: 'pacificada',
    potencialFinanceiro: 'muito_alto',
    potencialMercadologico: 'muito_alto',
    requisitosObjetivos: [
      'Ser contribuinte de ICMS',
      'Apurar PIS/COFINS sobre faturamento',
      'Possuir notas fiscais com destaque de ICMS',
    ],
    requisitosImpeditivos: [
      'Empresa optante pelo Simples Nacional (sem apuração separada de PIS/COFINS)',
      'Empresa que não destaca ICMS em suas operações',
    ],
    fundamentacaoLegal: 'RE 574.706/PR — Tema 69 de Repercussão Geral do STF. Art. 195, I, "b" da CF/88.',
    jurisprudenciaRelevante: 'STF, RE 574.706/PR, Rel. Min. Cármen Lúcia, julgado em 15/03/2017, com modulação de efeitos a partir de 15/03/2017.',
    parecerTecnicoJuridico: 'Tese pacificada pelo STF com repercussão geral. O ICMS destacado na nota fiscal não compõe o faturamento da empresa, sendo indevida sua inclusão na base de cálculo do PIS e da COFINS. A modulação de efeitos limita a restituição a créditos posteriores a 15/03/2017, salvo para quem já havia ajuizado ação antes dessa data. Risco jurídico baixo para novos pedidos. Recomenda-se ação judicial para recuperação dos valores pagos indevidamente nos últimos 5 anos.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: true,
    viaAdministrativa: false,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'Notas fiscais de saída com destaque de ICMS',
      'Apurações de PIS/COFINS (EFD-Contribuições)',
      'DCTF dos períodos envolvidos',
      'Comprovantes de recolhimento de PIS/COFINS',
    ],
    formulaEstimativaCredito: '(ICMS destacado nas NFs de saída) × (alíquota PIS 1,65% + COFINS 7,6%) × período (até 60 meses)',
    aplicavelComercio: true,
    aplicavelIndustria: true,
    aplicavelServico: false,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: false,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-01-15',
    dataAtualizacao: '2025-06-10',
    versao: 3,
    ativa: true,
  },
  {
    id: 'tese-002',
    nome: 'Exclusão do ISS da Base de Cálculo do PIS/COFINS',
    tributoEnvolvido: 'PIS/COFINS',
    tipo: 'tese_judicial',
    classificacao: 'judicial',
    potencialFinanceiro: 'alto',
    potencialMercadologico: 'alto',
    requisitosObjetivos: [
      'Ser prestador de serviços',
      'Ser contribuinte de ISS',
      'Apurar PIS/COFINS sobre faturamento',
    ],
    requisitosImpeditivos: [
      'Empresa optante pelo Simples Nacional',
      'Empresa que não recolhe ISS',
    ],
    fundamentacaoLegal: 'Tese derivada do RE 574.706/PR (Tema 69 STF). Aplicação analógica da exclusão do ICMS ao ISS. RE 592.616 (Tema 118).',
    jurisprudenciaRelevante: 'STF, RE 592.616/RS — Tema 118 de Repercussão Geral, ainda pendente de julgamento definitivo. TRFs com decisões favoráveis.',
    parecerTecnicoJuridico: 'Tese com forte fundamento jurídico baseada na ratio decidendi do RE 574.706 (exclusão do ICMS). O ISS, assim como o ICMS, é tributo que transita pela contabilidade da empresa sem configurar receita ou faturamento. Embora ainda não definitivamente julgada pelo STF, há forte tendência de acolhimento. Risco médio pela pendência de julgamento definitivo.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: true,
    viaAdministrativa: false,
    grauRisco: 'medio',
    documentosNecessarios: [
      'Notas fiscais de serviço com destaque de ISS',
      'Apurações de PIS/COFINS (EFD-Contribuições)',
      'Guias de recolhimento de ISS',
      'DCTF dos períodos envolvidos',
    ],
    formulaEstimativaCredito: '(ISS recolhido) × (alíquota PIS 1,65% + COFINS 7,6%) × período (até 60 meses)',
    aplicavelComercio: false,
    aplicavelIndustria: false,
    aplicavelServico: true,
    aplicavelContribuinteICMS: false,
    aplicavelContribuinteIPI: false,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-02-20',
    dataAtualizacao: '2025-05-15',
    versao: 2,
    ativa: true,
  },
  {
    id: 'tese-003',
    nome: 'Créditos de PIS/COFINS sobre Insumos (Conceito Amplo)',
    tributoEnvolvido: 'PIS/COFINS',
    tipo: 'recuperacao_indebito',
    classificacao: 'pacificada',
    potencialFinanceiro: 'muito_alto',
    potencialMercadologico: 'muito_alto',
    requisitosObjetivos: [
      'Estar no regime de Lucro Real (não cumulatividade)',
      'Possuir gastos com insumos essenciais ou relevantes à atividade',
    ],
    requisitosImpeditivos: [
      'Empresa no Simples Nacional',
      'Empresa no Lucro Presumido (regime cumulativo)',
    ],
    fundamentacaoLegal: 'REsp 1.221.170/PR — Tema 779 do STJ. Art. 3º das Leis 10.637/02 e 10.833/03.',
    jurisprudenciaRelevante: 'STJ, REsp 1.221.170/PR, Rel. Min. Napoleão Nunes Maia Filho, julgado em 22/02/2018. Conceito de insumo: essencialidade e relevância.',
    parecerTecnicoJuridico: 'O STJ definiu que insumo para fins de creditamento de PIS/COFINS deve ser analisado à luz dos critérios de essencialidade e relevância para a atividade econômica do contribuinte, superando as restrições impostas pelas INs SRF 247/02 e 404/04. Tese pacificada com amplo potencial de recuperação para empresas do Lucro Real que possuem gastos significativos com insumos não creditados anteriormente.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: false,
    viaAdministrativa: true,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'EFD-Contribuições dos últimos 5 anos',
      'Notas fiscais de aquisição de insumos',
      'Descrição detalhada do processo produtivo/operacional',
      'Planilha de custos e despesas operacionais',
    ],
    formulaEstimativaCredito: '(Valor dos insumos não creditados) × (alíquota PIS 1,65% + COFINS 7,6%) × período (até 60 meses)',
    aplicavelComercio: true,
    aplicavelIndustria: true,
    aplicavelServico: true,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: true,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: false,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-01-10',
    dataAtualizacao: '2025-04-20',
    versao: 2,
    ativa: true,
  },
  {
    id: 'tese-004',
    nome: 'Recuperação de ICMS-ST (Substituição Tributária) — Diferença de Base de Cálculo',
    tributoEnvolvido: 'ICMS',
    tipo: 'recuperacao_indebito',
    classificacao: 'pacificada',
    potencialFinanceiro: 'alto',
    potencialMercadologico: 'alto',
    requisitosObjetivos: [
      'Ser contribuinte de ICMS',
      'Operar com mercadorias sujeitas à substituição tributária',
      'Base de cálculo presumida superior à efetivamente praticada',
    ],
    requisitosImpeditivos: [
      'Empresa que não opera com ICMS-ST',
      'Estado que não permite restituição de ICMS-ST',
    ],
    fundamentacaoLegal: 'RE 593.849/MG — Tema 201 de Repercussão Geral do STF. Art. 150, §7º da CF/88.',
    jurisprudenciaRelevante: 'STF, RE 593.849/MG, Rel. Min. Edson Fachin, julgado em 19/10/2016. Direito à restituição quando a base presumida for superior à efetiva.',
    parecerTecnicoJuridico: 'O STF reconheceu o direito à restituição do ICMS-ST pago a maior quando a base de cálculo presumida for superior ao valor efetivamente praticado na operação. Tese pacificada com repercussão geral. A implementação depende da legislação estadual e dos procedimentos administrativos de cada UF. Recomenda-se análise caso a caso considerando a legislação do estado de atuação.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: false,
    viaAdministrativa: true,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'Notas fiscais de aquisição com ICMS-ST',
      'Notas fiscais de saída (preço efetivamente praticado)',
      'Apuração de ICMS-ST do período',
      'GIA/EFD ICMS-IPI',
    ],
    formulaEstimativaCredito: '(ICMS-ST recolhido com base presumida - ICMS devido com base efetiva) × período',
    aplicavelComercio: true,
    aplicavelIndustria: true,
    aplicavelServico: false,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: false,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: true,
    aplicavelPos2017: true,
    dataCriacao: '2024-03-01',
    dataAtualizacao: '2025-03-15',
    versao: 1,
    ativa: true,
  },
  {
    id: 'tese-005',
    nome: 'Exclusão do ICMS-ST da Base de Cálculo do PIS/COFINS',
    tributoEnvolvido: 'PIS/COFINS',
    tipo: 'exclusao_base',
    classificacao: 'judicial',
    potencialFinanceiro: 'alto',
    potencialMercadologico: 'alto',
    requisitosObjetivos: [
      'Ser contribuinte de ICMS',
      'Operar com mercadorias sujeitas à substituição tributária',
      'Apurar PIS/COFINS incluindo ICMS-ST na base',
    ],
    requisitosImpeditivos: [
      'Empresa optante pelo Simples Nacional',
      'Empresa que não opera com ICMS-ST',
    ],
    fundamentacaoLegal: 'Extensão do Tema 69 (RE 574.706/PR) ao ICMS-ST. REsp 1.896.678/RS — Tema 1125 do STJ.',
    jurisprudenciaRelevante: 'STJ, REsp 1.896.678/RS, Tema 1125, julgamento em andamento. Decisões favoráveis em TRFs.',
    parecerTecnicoJuridico: 'Tese derivada da exclusão do ICMS da base do PIS/COFINS. O ICMS-ST, por ser recolhido antecipadamente pelo substituto tributário, também não configura receita ou faturamento. Embora pendente de definição pelo STJ (Tema 1125), há forte fundamento jurídico e decisões favoráveis nos tribunais regionais. Risco médio pela ausência de decisão definitiva.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: true,
    viaAdministrativa: false,
    grauRisco: 'medio',
    documentosNecessarios: [
      'Notas fiscais com destaque de ICMS-ST',
      'EFD-Contribuições',
      'Apuração de PIS/COFINS',
      'Comprovantes de recolhimento',
    ],
    formulaEstimativaCredito: '(ICMS-ST incluído na base do PIS/COFINS) × (alíquotas PIS/COFINS) × período',
    aplicavelComercio: true,
    aplicavelIndustria: true,
    aplicavelServico: false,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: false,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-04-10',
    dataAtualizacao: '2025-05-20',
    versao: 2,
    ativa: true,
  },
  {
    id: 'tese-006',
    nome: 'Crédito de IPI na Aquisição de Insumos da Zona Franca de Manaus',
    tributoEnvolvido: 'IPI',
    tipo: 'credito_presumido',
    classificacao: 'pacificada',
    potencialFinanceiro: 'medio',
    potencialMercadologico: 'medio',
    requisitosObjetivos: [
      'Ser contribuinte de IPI',
      'Ser estabelecimento industrial',
      'Adquirir insumos de empresas da Zona Franca de Manaus',
    ],
    requisitosImpeditivos: [
      'Empresa que não industrializa',
      'Empresa que não adquire insumos da ZFM',
      'Empresa no Simples Nacional',
    ],
    fundamentacaoLegal: 'RE 592.891/SP — Tema 322 de Repercussão Geral do STF. Art. 153, §3º, II da CF/88.',
    jurisprudenciaRelevante: 'STF, RE 592.891/SP, Rel. Min. Rosa Weber, julgado em 25/04/2019. Direito ao crédito de IPI na aquisição de insumos isentos da ZFM.',
    parecerTecnicoJuridico: 'O STF reconheceu o direito ao crédito de IPI nas aquisições de insumos provenientes da Zona Franca de Manaus, mesmo quando estes são isentos ou com alíquota zero. Tese pacificada com repercussão geral. Aplicável a estabelecimentos industriais que adquirem matérias-primas, produtos intermediários e material de embalagem da ZFM.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: false,
    viaAdministrativa: true,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'Notas fiscais de aquisição de insumos da ZFM',
      'Livro de Registro de Entradas',
      'Apuração de IPI',
      'Comprovação da origem ZFM dos insumos',
    ],
    formulaEstimativaCredito: '(Valor dos insumos adquiridos da ZFM) × (alíquota IPI aplicável) × período',
    aplicavelComercio: false,
    aplicavelIndustria: true,
    aplicavelServico: false,
    aplicavelContribuinteICMS: false,
    aplicavelContribuinteIPI: true,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-05-15',
    dataAtualizacao: '2025-02-28',
    versao: 1,
    ativa: true,
  },
  {
    id: 'tese-007',
    nome: 'Recuperação de PIS/COFINS Monofásico — Revendedores',
    tributoEnvolvido: 'PIS/COFINS',
    tipo: 'recuperacao_indebito',
    classificacao: 'pacificada',
    potencialFinanceiro: 'alto',
    potencialMercadologico: 'muito_alto',
    requisitosObjetivos: [
      'Comercializar produtos sujeitos ao regime monofásico',
      'Ter recolhido PIS/COFINS sobre produtos monofásicos indevidamente',
    ],
    requisitosImpeditivos: [
      'Empresa que é o fabricante/importador (contribuinte substituto)',
    ],
    fundamentacaoLegal: 'Art. 2º da Lei 10.637/02 e Art. 2º da Lei 10.833/03. IN RFB 2.121/2022.',
    jurisprudenciaRelevante: 'Jurisprudência administrativa consolidada no CARF. Solução de Consulta COSIT nº 106/2014.',
    parecerTecnicoJuridico: 'No regime monofásico, a tributação de PIS/COFINS é concentrada no fabricante ou importador. Os revendedores (atacadistas e varejistas) têm alíquota zero. Muitas empresas, especialmente no Simples Nacional, recolhem indevidamente PIS/COFINS sobre esses produtos. A recuperação pode ser feita administrativamente via retificação de declarações. Tese pacificada com alto volume de recuperação no mercado.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: false,
    viaAdministrativa: true,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'Notas fiscais de compra e venda dos produtos monofásicos',
      'Classificação NCM dos produtos',
      'Apurações de PIS/COFINS ou DAS (Simples Nacional)',
      'EFD-Contribuições ou PGDAS-D',
    ],
    formulaEstimativaCredito: '(PIS/COFINS recolhido indevidamente sobre produtos monofásicos) × período (até 60 meses)',
    aplicavelComercio: true,
    aplicavelIndustria: false,
    aplicavelServico: false,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: false,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: true,
    aplicavelPos2017: true,
    dataCriacao: '2024-01-20',
    dataAtualizacao: '2025-06-01',
    versao: 3,
    ativa: true,
  },
  {
    id: 'tese-008',
    nome: 'Exclusão das Subvenções de ICMS da Base do IRPJ/CSLL',
    tributoEnvolvido: 'IRPJ/CSLL',
    tipo: 'exclusao_base',
    classificacao: 'judicial',
    potencialFinanceiro: 'alto',
    potencialMercadologico: 'medio',
    requisitosObjetivos: [
      'Estar no regime de Lucro Real',
      'Receber benefícios fiscais de ICMS (créditos presumidos, redução de base, etc.)',
      'Ter incluído subvenções na base do IRPJ/CSLL',
    ],
    requisitosImpeditivos: [
      'Empresa no Simples Nacional',
      'Empresa no Lucro Presumido',
      'Empresa que não recebe benefícios fiscais de ICMS',
    ],
    fundamentacaoLegal: 'EREsp 1.517.492/PR — STJ. Art. 30 da Lei 12.973/2014. LC 160/2017.',
    jurisprudenciaRelevante: 'STJ, EREsp 1.517.492/PR, 1ª Seção, julgado em 08/11/2017. Tema 1182 do STJ (pendente).',
    parecerTecnicoJuridico: 'A discussão envolve a natureza jurídica dos incentivos fiscais de ICMS concedidos pelos estados e sua tributação pelo IRPJ e CSLL. O STJ tem entendido que créditos presumidos de ICMS não podem ser tributados pela União, sob pena de violação ao pacto federativo. A LC 160/2017 e a Lei 14.789/2023 trouxeram novas regras. Análise deve considerar o tipo específico de benefício e o período.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: true,
    viaAdministrativa: false,
    grauRisco: 'medio',
    documentosNecessarios: [
      'Demonstrativo dos benefícios fiscais de ICMS recebidos',
      'LALUR/LACS',
      'ECF dos períodos envolvidos',
      'Legislação estadual do benefício',
    ],
    formulaEstimativaCredito: '(Valor das subvenções de ICMS) × (alíquota IRPJ 25% + CSLL 9%) × período',
    aplicavelComercio: true,
    aplicavelIndustria: true,
    aplicavelServico: false,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: false,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: false,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-06-01',
    dataAtualizacao: '2025-04-10',
    versao: 2,
    ativa: true,
  },
  {
    id: 'tese-009',
    nome: 'Contribuição Previdenciária sobre Verbas Indenizatórias',
    tributoEnvolvido: 'Contribuição Previdenciária',
    tipo: 'recuperacao_indebito',
    classificacao: 'pacificada',
    potencialFinanceiro: 'medio',
    potencialMercadologico: 'alto',
    requisitosObjetivos: [
      'Possuir folha de pagamento',
      'Ter recolhido contribuição previdenciária sobre verbas indenizatórias',
    ],
    requisitosImpeditivos: [
      'Empresa sem empregados',
      'Empresa que já excluiu verbas indenizatórias da base',
    ],
    fundamentacaoLegal: 'REsp 1.230.957/RS — Temas 738 e 739 do STJ. Art. 28 da Lei 8.212/91.',
    jurisprudenciaRelevante: 'STJ, REsp 1.230.957/RS, Rel. Min. Mauro Campbell Marques, julgado em 26/02/2014. Recurso repetitivo.',
    parecerTecnicoJuridico: 'O STJ definiu em recurso repetitivo que diversas verbas de natureza indenizatória não integram a base de cálculo da contribuição previdenciária patronal. Incluem-se: terço constitucional de férias, aviso prévio indenizado, 15 primeiros dias de auxílio-doença, entre outras. Tese pacificada com possibilidade de recuperação administrativa. Alto potencial para empresas com folha de pagamento significativa.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: false,
    viaAdministrativa: true,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'Folhas de pagamento dos últimos 5 anos',
      'GFIP/eSocial',
      'Demonstrativo de verbas indenizatórias pagas',
      'GPS/DARF de contribuição previdenciária',
    ],
    formulaEstimativaCredito: '(Verbas indenizatórias) × (alíquota patronal 20% + RAT + Terceiros) × período',
    aplicavelComercio: true,
    aplicavelIndustria: true,
    aplicavelServico: true,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: true,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-02-01',
    dataAtualizacao: '2025-05-05',
    versao: 2,
    ativa: true,
  },
  {
    id: 'tese-010',
    nome: 'Limite de 20 Salários Mínimos para Contribuições a Terceiros (Sistema S)',
    tributoEnvolvido: 'Contribuições a Terceiros',
    tipo: 'tese_judicial',
    classificacao: 'controversa',
    potencialFinanceiro: 'alto',
    potencialMercadologico: 'alto',
    requisitosObjetivos: [
      'Possuir folha de pagamento acima de 20 salários mínimos',
      'Recolher contribuições a terceiros (SESI, SENAI, SESC, SENAC, etc.)',
    ],
    requisitosImpeditivos: [
      'Empresa no Simples Nacional',
      'Empresa com folha de pagamento inferior a 20 salários mínimos',
    ],
    fundamentacaoLegal: 'Art. 4º da Lei 6.950/81 c/c Art. 1º do DL 2.318/86. Tema 1079 do STJ.',
    jurisprudenciaRelevante: 'STJ, Tema 1079, REsp 1.898.532/CE, pendente de julgamento definitivo. Decisões divergentes nos TRFs.',
    parecerTecnicoJuridico: 'A tese sustenta que o teto de 20 salários mínimos previsto na Lei 6.950/81 para a base de cálculo das contribuições parafiscais (Sistema S, INCRA, Salário-Educação) não foi revogado pelo DL 2.318/86, que teria removido o limite apenas para a contribuição previdenciária patronal. Tese controversa com decisões divergentes. O STJ ainda não concluiu o julgamento do Tema 1079. Risco alto, mas com potencial financeiro significativo.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: true,
    viaAdministrativa: false,
    grauRisco: 'alto',
    documentosNecessarios: [
      'Folhas de pagamento',
      'GFIP/eSocial',
      'GPS/DARF de contribuições a terceiros',
      'Demonstrativo da base de cálculo',
    ],
    formulaEstimativaCredito: '(Contribuições a terceiros recolhidas - Contribuições limitadas a 20 SM) × período',
    aplicavelComercio: true,
    aplicavelIndustria: true,
    aplicavelServico: true,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: true,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-07-01',
    dataAtualizacao: '2025-06-15',
    versao: 2,
    ativa: true,
  },
  {
    id: 'tese-011',
    nome: 'Retenção Indevida de ISS — Serviços Não Listados na LC 116/03',
    tributoEnvolvido: 'ISS',
    tipo: 'recuperacao_indebito',
    classificacao: 'administrativa',
    potencialFinanceiro: 'medio',
    potencialMercadologico: 'medio',
    requisitosObjetivos: [
      'Ser prestador de serviços',
      'Ter sofrido retenção de ISS sobre serviços não listados na LC 116/03',
    ],
    requisitosImpeditivos: [
      'Serviços expressamente listados na LC 116/03',
    ],
    fundamentacaoLegal: 'Art. 1º da LC 116/2003. Lista de Serviços anexa à LC 116/03 (taxatividade).',
    jurisprudenciaRelevante: 'RE 784.439/DF — Tema 296 STF. A lista de serviços da LC 116/03 é taxativa, admitindo interpretação extensiva.',
    parecerTecnicoJuridico: 'O STF definiu que a lista de serviços da LC 116/03 é taxativa, embora admita interpretação extensiva de cada item. Serviços que não se enquadram em nenhum dos itens da lista não podem ser tributados pelo ISS. Empresas que sofreram retenção indevida podem buscar a restituição administrativamente junto ao município.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: false,
    viaAdministrativa: true,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'Notas fiscais de serviço com retenção de ISS',
      'Contratos de prestação de serviço',
      'Comprovantes de retenção',
      'Descrição detalhada dos serviços prestados',
    ],
    formulaEstimativaCredito: '(ISS retido indevidamente) × período',
    aplicavelComercio: false,
    aplicavelIndustria: false,
    aplicavelServico: true,
    aplicavelContribuinteICMS: false,
    aplicavelContribuinteIPI: false,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: true,
    aplicavelPos2017: true,
    dataCriacao: '2024-08-01',
    dataAtualizacao: '2025-03-20',
    versao: 1,
    ativa: true,
  },
  {
    id: 'tese-012',
    nome: 'Créditos de ICMS sobre Energia Elétrica e Telecomunicações',
    tributoEnvolvido: 'ICMS',
    tipo: 'recuperacao_indebito',
    classificacao: 'pacificada',
    potencialFinanceiro: 'medio',
    potencialMercadologico: 'medio',
    requisitosObjetivos: [
      'Ser contribuinte de ICMS',
      'Ser estabelecimento industrial ou equiparado',
      'Consumir energia elétrica no processo de industrialização',
    ],
    requisitosImpeditivos: [
      'Empresa exclusivamente prestadora de serviços',
      'Empresa no Simples Nacional',
    ],
    fundamentacaoLegal: 'Art. 33, II, "b" da LC 87/96. Convênio ICMS 01/2024.',
    jurisprudenciaRelevante: 'Jurisprudência consolidada nos tribunais estaduais. Tema definido pela LC 87/96 com alterações da LC 102/2000.',
    parecerTecnicoJuridico: 'Estabelecimentos industriais têm direito ao crédito de ICMS sobre energia elétrica consumida no processo de industrialização. Muitas empresas não aproveitam integralmente esse crédito por desconhecimento ou interpretação restritiva. A partir de 2024, com as alterações da reforma tributária, o creditamento tende a ser ampliado. Recomenda-se revisão das apurações dos últimos 5 anos.',
    prazoPrescricional: '5 anos',
    necessidadeAcaoJudicial: false,
    viaAdministrativa: true,
    grauRisco: 'baixo',
    documentosNecessarios: [
      'Contas de energia elétrica',
      'Laudo técnico de consumo de energia no processo industrial',
      'EFD ICMS-IPI',
      'Apuração de ICMS',
    ],
    formulaEstimativaCredito: '(ICMS sobre energia elétrica no processo industrial) × período',
    aplicavelComercio: false,
    aplicavelIndustria: true,
    aplicavelServico: false,
    aplicavelContribuinteICMS: true,
    aplicavelContribuinteIPI: true,
    aplicavelLucroReal: true,
    aplicavelLucroPresumido: true,
    aplicavelSimplesNacional: false,
    aplicavelPos2017: true,
    dataCriacao: '2024-09-01',
    dataAtualizacao: '2025-01-15',
    versao: 1,
    ativa: true,
  },
];
